#!/bin/bash
set -euo pipefail

# =============================================================================
# Real-Auth E2E Test Runner
# =============================================================================
# Runs Playwright tests against local Supabase (Docker) with real credentials.
# Unlike the standard E2E tests (E2E_TESTING=true), this tests actual auth paths:
#
#   1. Supabase login (signInWithPassword → RS256 JWT via JWKS)
#   2. Platform Hub OAuth 2.1 (authorization code → HS256 JWT via SESSION_TOKEN_SECRET)
#   3. Cross-app SSO (cookie propagation + middleware verification)
#
# Prerequisites:
#   brew install --cask docker
#   brew install supabase/tap/supabase
#
# Usage:
#   pnpm test:e2e:real-auth              # Run all real-auth tests
#   pnpm test:e2e:real-auth -- --headed  # Run with visible browser
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[real-auth]${NC} $*"; }
warn() { echo -e "${YELLOW}[real-auth]${NC} $*"; }
error() { echo -e "${RED}[real-auth]${NC} $*"; }
success() { echo -e "${GREEN}[real-auth]${NC} $*"; }

# Track background PIDs for cleanup
DEV_PID=""

cleanup() {
  log "Cleaning up..."
  if [ -n "$DEV_PID" ] && kill -0 "$DEV_PID" 2>/dev/null; then
    kill "$DEV_PID" 2>/dev/null || true
    wait "$DEV_PID" 2>/dev/null || true
  fi
  # Restore original .env.local files
  for app in bingo trivia platform-hub; do
    if [ -f "apps/$app/.env.local.real-auth-backup" ]; then
      mv "apps/$app/.env.local.real-auth-backup" "apps/$app/.env.local"
      log "Restored apps/$app/.env.local"
    fi
  done
  log "Cleanup complete"
}

trap cleanup EXIT INT TERM

# =============================================================================
# 1. Verify prerequisites
# =============================================================================
log "Checking prerequisites..."

if ! command -v supabase &>/dev/null; then
  error "Supabase CLI not found. Install with: brew install supabase/tap/supabase"
  exit 1
fi

if ! command -v docker &>/dev/null; then
  error "Docker not found. Install with: brew install --cask docker"
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  error "Docker is not running. Start Docker Desktop first."
  exit 1
fi

success "Prerequisites OK"

# =============================================================================
# 2. Start local Supabase (idempotent — skips if already running)
# =============================================================================
log "Starting local Supabase..."

# Check if already running using JSON output (robust against format changes)
if supabase status -o json 2>/dev/null | grep -q '"API_URL"'; then
  warn "Local Supabase already running, reusing existing instance"
else
  supabase start
  success "Local Supabase started"
fi

# =============================================================================
# 3. Extract credentials from local Supabase
# =============================================================================
log "Extracting local Supabase credentials..."

# Use `supabase status -o env` for reliable parsing.
# The old `awk '{print $NF}'` approach broke when the CLI switched to
# box-drawing table characters in its pretty-printed output.
# `-o env` outputs clean KEY=VALUE lines that are trivial to parse.
eval "$(supabase status -o env 2>/dev/null)"

LOCAL_URL="${API_URL:-}"
LOCAL_ANON_KEY="${ANON_KEY:-}"
LOCAL_SERVICE_KEY="${SERVICE_ROLE_KEY:-}"
LOCAL_JWT_SECRET="${JWT_SECRET:-}"

if [ -z "$LOCAL_URL" ] || [ -z "$LOCAL_ANON_KEY" ] || [ -z "$LOCAL_SERVICE_KEY" ]; then
  error "Failed to extract Supabase credentials. Check 'supabase status -o env' output."
  exit 1
fi

success "Supabase credentials extracted"
log "  API URL: $LOCAL_URL"
log "  Anon key: ${LOCAL_ANON_KEY:0:20}..."

# =============================================================================
# 4. Generate random SESSION_TOKEN_SECRET for this run
# =============================================================================
SESSION_SECRET=$(openssl rand -hex 32)
log "Generated SESSION_TOKEN_SECRET for this run"

# =============================================================================
# 5. Write .env.real-auth (gitignored)
# =============================================================================
cat > .env.real-auth << EOF
# Auto-generated by scripts/e2e-real-auth.sh
# Do NOT commit this file (it's in .gitignore)
NEXT_PUBLIC_SUPABASE_URL=$LOCAL_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$LOCAL_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$LOCAL_SERVICE_KEY
SUPABASE_JWT_SECRET=$LOCAL_JWT_SECRET
SESSION_TOKEN_SECRET=$SESSION_SECRET
NEXT_PUBLIC_APP_URL=http://localhost:3002
NEXT_PUBLIC_BINGO_URL=http://localhost:3000
NEXT_PUBLIC_TRIVIA_URL=http://localhost:3001
NEXT_PUBLIC_PLATFORM_HUB_URL=http://localhost:3002
NEXT_PUBLIC_OAUTH_CLIENT_ID=0d87a03a-d90a-4ccc-a46b-85fdd8d53c21
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002
EOF

success "Wrote .env.real-auth"

# =============================================================================
# 6. Backup existing .env.local and install real-auth env
# =============================================================================
log "Setting up app environment files..."

for app in bingo trivia platform-hub; do
  if [ -f "apps/$app/.env.local" ]; then
    cp "apps/$app/.env.local" "apps/$app/.env.local.real-auth-backup"
  fi
  cp .env.real-auth "apps/$app/.env.local"
  log "  apps/$app/.env.local updated"
done

# =============================================================================
# 7. Kill any existing dev servers on default ports
# =============================================================================
log "Checking for existing servers on ports 3000, 3001, 3002..."
for port in 3000 3001 3002; do
  pid=$(lsof -ti:"$port" 2>/dev/null || true)
  if [ -n "$pid" ]; then
    warn "Killing existing process on port $port (PID: $pid)"
    kill "$pid" 2>/dev/null || true
  fi
done
sleep 1

# =============================================================================
# 8. Start dev servers WITHOUT E2E_TESTING flag
# =============================================================================
log "Starting dev servers (NO E2E_TESTING flag)..."

# NOTE: We intentionally do NOT set E2E_TESTING=true here.
# This forces the apps to use real Supabase auth and real JWT verification.
pnpm dev &
DEV_PID=$!

# =============================================================================
# 9. Wait for servers to be ready
# =============================================================================
log "Waiting for servers to start..."

wait_for_server() {
  local url=$1
  local name=$2
  local max_attempts=60
  local attempt=0

  while [ $attempt -lt $max_attempts ]; do
    if curl -s -o /dev/null -w "%{http_code}" "$url" 2>/dev/null | grep -qE "^[23]"; then
      success "$name ready at $url"
      return 0
    fi
    attempt=$((attempt + 1))
    sleep 2
  done

  error "$name not ready after ${max_attempts} attempts at $url"
  return 1
}

wait_for_server "http://localhost:3000" "Bingo"
wait_for_server "http://localhost:3001" "Trivia"
wait_for_server "http://localhost:3002" "Platform Hub"

success "All servers ready"

# =============================================================================
# 10. Export env vars for Playwright global setup and tests
# =============================================================================
export NEXT_PUBLIC_SUPABASE_URL="$LOCAL_URL"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="$LOCAL_ANON_KEY"
export SUPABASE_SERVICE_ROLE_KEY="$LOCAL_SERVICE_KEY"
export SUPABASE_JWT_SECRET="$LOCAL_JWT_SECRET"
export SESSION_TOKEN_SECRET="$SESSION_SECRET"

# Disable E2E bypass — forces Playwright config to NOT set E2E_TESTING=true.
# This ensures the Playwright process (test code) uses real Supabase credentials.
# The dev servers already lack E2E_TESTING since .env.real-auth doesn't include it.
export E2E_TESTING=false

# =============================================================================
# 11. Run real-auth tests only
# =============================================================================
log "Running real-auth Playwright tests..."

# Pass through any additional args (e.g., --headed, --debug)
npx playwright test --project=real-auth "$@"
TEST_EXIT_CODE=$?

if [ $TEST_EXIT_CODE -eq 0 ]; then
  success "All real-auth tests passed!"
else
  error "Some real-auth tests failed (exit code: $TEST_EXIT_CODE)"
fi

exit $TEST_EXIT_CODE
