#!/bin/bash

# =============================================================================
# E2E Test Environment Setup for Git Worktrees
# =============================================================================
#
# This script sets up the E2E testing environment for a git worktree.
# It calculates the port offset based on the worktree path hash and creates
# the necessary configuration files and helper scripts.
#
# Usage:
#   ./scripts/setup-worktree-e2e.sh
#
# What it does:
# 1. Detects if running in a worktree (vs main repo)
# 2. Calculates deterministic port offset from worktree path
# 3. Creates .env.e2e with port configuration
# 4. Creates start-e2e-servers.sh helper script
# 5. Displays configuration summary
#
# Port Allocation:
# - Main repo: 3000, 3001 (no offset)
# - Worktrees: 3000 + offset, 3001 + offset
# - Offset is deterministic (same worktree path = same offset)
# - Max 333 unique worktrees (offsets 0, 3, 6, ..., 996)
#
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the directory where this script lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo -e "${BLUE}=== E2E Test Environment Setup ===${NC}"
echo ""

# -----------------------------------------------------------------------------
# Step 1: Detect worktree status
# -----------------------------------------------------------------------------

GIT_PATH="$REPO_ROOT/.git"

if [ ! -e "$GIT_PATH" ]; then
  echo -e "${RED}Error: Not in a git repository${NC}"
  exit 1
fi

IS_WORKTREE=false
WORKTREE_PATH=""

if [ -f "$GIT_PATH" ]; then
  # .git is a file - this is a worktree
  IS_WORKTREE=true
  WORKTREE_PATH="$REPO_ROOT"
  echo -e "${GREEN}Detected: Git worktree${NC}"
  echo "  Path: $WORKTREE_PATH"
elif [ -d "$GIT_PATH" ]; then
  # .git is a directory - this is the main repo
  echo -e "${GREEN}Detected: Main repository${NC}"
  echo "  Path: $REPO_ROOT"
fi

# -----------------------------------------------------------------------------
# Step 2: Calculate port offset
# -----------------------------------------------------------------------------

if [ "$IS_WORKTREE" = true ]; then
  # Calculate hash-based port offset for worktree
  # Use SHA-256 hash of the worktree path, take first 8 hex chars
  HASH=$(echo -n "$WORKTREE_PATH" | shasum -a 256 | cut -c1-8)
  # Convert hex to decimal
  HASH_INT=$((16#$HASH))
  # Map to 0-332 range, then multiply by 3
  OFFSET_INDEX=$((HASH_INT % 333))
  PORT_OFFSET=$((OFFSET_INDEX * 3))
else
  # Main repo uses no offset
  PORT_OFFSET=0
fi

BINGO_PORT=$((3000 + PORT_OFFSET))
TRIVIA_PORT=$((3001 + PORT_OFFSET))

echo ""
echo -e "${BLUE}Port Configuration:${NC}"
echo "  Offset: $PORT_OFFSET"
echo "  Bingo:  http://localhost:$BINGO_PORT"
echo "  Trivia: http://localhost:$TRIVIA_PORT"

# -----------------------------------------------------------------------------
# Step 3: Create .env.e2e file
# -----------------------------------------------------------------------------

ENV_FILE="$REPO_ROOT/.env.e2e"

cat > "$ENV_FILE" << EOF
# =============================================================================
# E2E Testing Configuration
# =============================================================================
# Generated by: scripts/setup-worktree-e2e.sh
# Generated at: $(date -Iseconds)
#
# This file contains port configuration for E2E testing in this worktree.
# Source this file before starting dev servers or running tests:
#
#   source .env.e2e
#   pnpm dev
#   pnpm test:e2e
#
# Or use the generated helper script:
#
#   ./start-e2e-servers.sh
#
# =============================================================================

# Port Configuration
export E2E_PORT_BASE=$BINGO_PORT
export E2E_BINGO_PORT=$BINGO_PORT
export E2E_TRIVIA_PORT=$TRIVIA_PORT

# Individual app port variables (used by Next.js)
export BINGO_PORT=$BINGO_PORT
export TRIVIA_PORT=$TRIVIA_PORT

# E2E Testing flag
export E2E_TESTING=true

# E2E JWT signing secret (required when E2E_TESTING=true)
export E2E_JWT_SECRET=e2e-test-secret-key-that-is-at-least-32-characters-long

# Worktree metadata
export WORKTREE_PATH="$WORKTREE_PATH"
export PORT_OFFSET=$PORT_OFFSET
EOF

echo ""
echo -e "${GREEN}Created: .env.e2e${NC}"

# -----------------------------------------------------------------------------
# Step 4: Create helper script to start servers
# -----------------------------------------------------------------------------

HELPER_SCRIPT="$REPO_ROOT/start-e2e-servers.sh"

cat > "$HELPER_SCRIPT" << 'SCRIPT_EOF'
#!/bin/bash

# =============================================================================
# Start E2E Testing Servers
# =============================================================================
# This script starts both dev servers with the correct ports for this
# worktree's E2E testing environment.
#
# Usage:
#   ./start-e2e-servers.sh
#
# To stop servers:
#   pkill -f "next dev"
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source the E2E environment
if [ -f "$SCRIPT_DIR/.env.e2e" ]; then
  source "$SCRIPT_DIR/.env.e2e"
else
  echo "Error: .env.e2e not found. Run scripts/setup-worktree-e2e.sh first."
  exit 1
fi

echo "Starting E2E testing servers..."
echo "  Bingo:  http://localhost:$BINGO_PORT"
echo "  Trivia: http://localhost:$TRIVIA_PORT"
echo ""

# Start servers in background
cd "$SCRIPT_DIR"

echo "Starting Bingo (port $BINGO_PORT)..."
PORT=$BINGO_PORT pnpm --filter @joolie-boolie/bingo dev &

echo "Starting Trivia (port $TRIVIA_PORT)..."
PORT=$TRIVIA_PORT pnpm --filter @joolie-boolie/trivia dev &

echo ""
echo "All servers starting in background."
echo "To stop: pkill -f 'next dev'"
echo ""
echo "Waiting for servers to be ready..."
sleep 5

# Check if servers are responding
check_server() {
  local url=$1
  local name=$2
  if curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200\|302"; then
    echo "  $name: Ready"
  else
    echo "  $name: Still starting..."
  fi
}

check_server "http://localhost:$BINGO_PORT" "Bingo"
check_server "http://localhost:$TRIVIA_PORT" "Trivia"

echo ""
echo "Run E2E tests with: pnpm test:e2e"
SCRIPT_EOF

chmod +x "$HELPER_SCRIPT"

echo -e "${GREEN}Created: start-e2e-servers.sh${NC}"

# -----------------------------------------------------------------------------
# Step 5: Add .env.e2e and helper to .gitignore if not already there
# -----------------------------------------------------------------------------

GITIGNORE="$REPO_ROOT/.gitignore"

add_to_gitignore() {
  local pattern=$1
  if ! grep -q "^${pattern}$" "$GITIGNORE" 2>/dev/null; then
    echo "$pattern" >> "$GITIGNORE"
    echo -e "${YELLOW}Added to .gitignore: $pattern${NC}"
  fi
}

add_to_gitignore ".env.e2e"
add_to_gitignore "start-e2e-servers.sh"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

echo ""
echo -e "${BLUE}=== Setup Complete ===${NC}"
echo ""
echo "To start E2E testing servers:"
echo "  ./start-e2e-servers.sh"
echo ""
echo "Or manually:"
echo "  source .env.e2e"
echo "  PORT=\$BINGO_PORT pnpm --filter @joolie-boolie/bingo dev &"
echo "  PORT=\$TRIVIA_PORT pnpm --filter @joolie-boolie/trivia dev &"
echo ""
echo "To run E2E tests:"
echo "  pnpm test:e2e"
echo ""
echo "Playwright will automatically detect the port configuration."
echo ""
